---
- name: export LC_ALL
  shell: export LC_ALL="en_US.UTF-8"

- name: export LC_CTYPE
  shell: export LC_CTYPE="en_US.UTF-8"

- name: Install Python dependencies
  shell: pip3 install -r /usr/bin/dcm/dcm-python/requirements.txt
  when: not update_module

- name: Install requests package in pip3
  shell: pip3 install requests
  when: not update_module

- name: Install flask-swagger package in pip3
  shell: pip3 install flask-swagger
  when: not update_module

- name: Remove dcm.service file if exists
  file:
    path: /etc/systemd/system/dcm.service
    state: absent 

- name: Create start-up service for DCM REST Client
  script: create_dcm_service.sh {{ansible_user}} {{zookeeper_ip_address}}

- name: Start DCM REST Client service
  shell: systemctl start dcm.service

- name: Press enter to continue
  pause: prompt='Press enter to continue'
  when: prompt_when_finishes_tasks
