---
- name: export LC_ALL
  shell: export LC_ALL="en_US.UTF-8"

- name: export LC_CTYPE
  shell: export LC_CTYPE="en_US.UTF-8"

- name: Install Python dependencies
  shell: pip3 install -r /usr/bin/dcm/dcm-site-plugin/requirements.txt
  when: not update_module

- name: Install requests package in pip3
  shell: pip3 install requests
  when: not update_module

- name: Install flask-swagger package in pip3
  shell: pip3 install flask-swagger
  when: not update_module

- name: Remove dcm_site_plugin.service file if exists
  file:
    path: /etc/systemd/system/dcm_site_plugin.service
    state: absent 

- name: Create start-up service for DCM Site Plugin REST Client
  script: create_site_plugin_service.sh {{ansible_user}} {{ansible_host}} {{spanish_plugin_port}} {{kafka_topics_script_route}}
  when: site == "spain"

- name: Create start-up service for DCM Site Plugin REST Client
  script: create_site_plugin_service.sh {{ansible_user}} {{ansible_host}} {{italian_plugin_port}} {{kafka_topics_script_route}}
  when: site == "italy"

- name: Create start-up service for DCM Site Plugin REST Client
  script: create_site_plugin_service.sh {{ansible_user}} {{ansible_host}} {{french_plugin_port}} {{kafka_topics_script_route}}
  when: site == "france"

- name: Create start-up service for DCM Site Plugin REST Client
  script: create_site_plugin_service.sh {{ansible_user}} {{ansible_host}} {{greek_plugin_port}} {{kafka_topics_script_route}}
  when: site == "greece"

- name: Start DCM Site Plugin REST Client service
  shell: systemctl start dcm_site_plugin.service

- name: Press enter to continue
  pause: prompt='Press enter to continue'
  when: prompt_when_finishes_tasks
